language: php
php:            # When adding or removing php versions to test,
  #- 5.5         # make sure the number of tested versions is 
  #- 5.6         # updated in:
  - hhvm        # .scrutinizer.yml (tools: external_code_coverage: runs:)
  
install:
  - composer update

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN=59be07e897f3abafc334411ec14096ec4b39a816d43f5a45e072af854e42cef8 ./vendor/bin/test-reporter
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
