@extends('layouts.default')

@section('head')
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js"></script>
<script src="//cdn.jsdelivr.net/lodash/2.4.1/lodash.underscore.min.js"></script>
<script type="text/javascript" src="http://code.angularjs.org/1.2.9/angular-resource.min.js"></script>
<script type="text/javascript" src="/custom_assets/entityretrieval.js"></script>	
<script type="text/javascript" src="/custom_assets/angular-moment.js"></script>
<script type="text/javascript" src="/custom_assets/moment.js"></script>
<link rel="stylesheet" type="text/css" href="/custom_assets/custom.css"></link>
@stop

@section('content')
<div ng-app="entityRetrieval" ng-controller="unitByIdCtrl">
	<!-- Main column with results -->
	@include('layouts.flashdata')
 	<div class="row">
		<div class="ng-scope disabled pull-left">
			<ul style="margin-left: 20px;" class="pagination ng-isolate-scope">
				<li><a ng-click="previousId()">Previous</a></li> 
				<li><a ng-click="nextId()">Next</a></li> 
			</ul>
		</div>
	</div>
	<div class="mainContainer">
		<div class="bordered">
			<div class="row">
           		<div class="col-md-8">
           			<h2>@{{unit._id}}</h2>
           			<label class="ann-label">Title: </label>@{{unit.title}}<br>
					<label class="ann-label">Document type: </label>@{{unit.documentType}}<br>
					<label class="ann-label">Created at:  </label>@{{unit.created_at}} <br>
         		</div>
   	     	</div>
			<div>
				<pre>@{{unit.content | json}}</pre>
			</div>
		</div>
		<div class="bordered">
			<div class="row" ng-show="annotations.length >= 1">
				<div class="pull-left">
					<span class="badge annotationbadge">@{{annotations.length}}</span>
				</div>
				<div class="col-md-2">
					<a ng-click="setAnnotationsVisible()"><h4> Annotations</h4></a>			
				</div>
				<div class="col-md-12" ng-repeat="annotation in annotations" ng-show="annotationsVisible">
					<div class="items">
						<div class="row">
							<div class="col-md-9">
								<a ng-click="gotoAnnotation(annotation._id)"><h4>@{{annotation.format}} @{{annotation.domain}}</h4></a>
								<label class="ann-label">By agent:  </label><a ng-click="gotoWorker(annotation.crowdAgent_id)">@{{annotation.crowdAgent_id}}</a><br>
								<label class="ann-label">Part of:  </label>@{{annotation.job_id}}<br>
								<label class="ann-label">Generated by:  </label>@{{annotation.activity_id}}
							</div>
							<div class="col-md-3 anntime">
								<label class="ann-label">Accepted: </label>@{{annotation.acceptTime}}<br>
								<label class="ann-label">Submitted: </label>@{{annotation.submitTime}}
							</div>
						</div>
						<div>
							<pre>@{{annotation.content | json}}</pre>
						</div>				
					</div>	
				</div>
			</div>
		</div>
	</div>
</div>
@stop

@section('end_javascript')
	<script>
				
	</script>
@stop