<div data-pagination="annotation in annotations" data-num-pages="numPages()" 
      data-current-page="currentPage" data-max-size="maxSize"  
      data-boundary-links="true"></div>
<div ng-repeat="annotation in annotations" class="items">
	<div class="row">
		<div class="col-md-9">
			<a ng-click="gotoAnnotation(annotation._id)"><h4>@{{annotation.format}} @{{annotation.domain}}</h4></a>
			<label class="ann-label">Unit:  </label><a ng-click="gotoUnit(annotation.unit_id)">@{{annotation.unit_id}}</a><br>
			<label class="ann-label">Part of:  </label>@{{annotation.job_id}}<br>
			<label class="ann-label">Generated by:  </label>@{{annotation.activity_id}}
		</div>
		<div class="col-md-3 anntime">
			<label class="ann-label">Accepted: </label>@{{annotation.acceptTime}}<br>
			<label class="ann-label">Submitted: </label>@{{annotation.submitTime}}
		</div>
	</div>
	<div>
		<pre style="height: 200px;">@{{annotation.content | json}}</pre>
	</div>
</div>