<?php namespace Api\enrichment;

use \BaseController as BaseController;
use \Input as Input;
use \URL as URL;

use \SoftwareComponents\ResultImporter as ResultImporter;
use \SoftwareComponents\DIVEUnitsImporter as DIVEUnitsImporter;

use \Exception;

class apiStatus extends BaseController
{
    public function getCapabilities()
    {
      // This list is generated by hand, but should be loaded from a catalog
      // of available templates.
      return [
                "status"  => "success",
                "message" => "Listing capabilities of CrowdTruth data enrichment",
                "capabilities" => [
                    [
                      "id" => "template1",
                      "parameters" => [
                        [ "type" => "string", "name" => "location" ],
                        [ "type" => "string", "name" => "synopsis" ]
                      ],
                      "description" => "This template adds ? to data"
                    ]
                ]
             ];
    }

    public function getStatus()
    {
      return [
                "status"  => "success",
                "message" => "CrowdTruth data enrichment is alive"
             ];
    }
}
?>
