<?php namespace Api\enrichment;

use \BaseController as BaseController;
use \Input as Input;
use \URL as URL;
use \Template as Template;

use \SoftwareComponents\ResultImporter as ResultImporter;
use \SoftwareComponents\DIVEUnitsImporter as DIVEUnitsImporter;

use \Exception;

/**
 * This class implements the 'status' calls from the Enrichment API. For more
 * details on the Enrichment API see:
 * https://github.com/beeldengeluid/labs-enrichment-api/
 */
class apiStatus extends BaseController
{
    // This function implements the GET /capabilities API call
    public function getCapabilities()
    {
      // This list is generated by hand, but should be loaded from a catalog
      // of available templates.
      $templates = \Template::where("parameters", 'exists', true)->where("description", 'exists', true)->get()->toArray();
      $capabilities = array();
      if ($templates == NULL) {
        return [
                "status"  => "error",
                "message" => "CrowdTruth has no capabilities available for data enrichment",
                "capabilities" => [
                ]
             ];
      }
      foreach ($templates as $template) {
        $newCapability = array();
        $newCapability["id"] = $template["_id"];
        $newCapability["description"] = $template["description"];
        $newCapability["parameters"] = array();
        $newCapability["provides"] = array();
        foreach ($template["parameters"]["input"] as $parameter) {
          $newParameter = array();
          $newParameter["type"] = $parameter["type"];
          $newParameter["name"] = $parameter["name"];
          $newParameter["description"] = $parameter["description"];
          array_push($newCapability["parameters"], $newParameter);
        }
        foreach ($template["parameters"]["output"] as $parameter) {
          $newParameter = array();
          $newParameter["type"] = $parameter["type"];
          $newParameter["name"] = $parameter["name"];
          $newParameter["description"] = $parameter["description"];
          array_push($newCapability["provides"], $newParameter);
        }
        array_push($capabilities, $newCapability);
      }
        return [
          "status"  => "success",
          "message" => "Listing capabilities of CrowdTruth data enrichment",
          "capabilities" => $capabilities
        ];
    }

    // This function implements the GET /status API call
    public function getStatus()
    {
      return [
                "status"  => "success",
                "message" => "CrowdTruth data enrichment is alive"
             ];
    }
}
?>
