@extends('layouts.default')

@section('head')
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js"></script>
<script src="//cdn.jsdelivr.net/lodash/2.4.1/lodash.underscore.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular-route.js"></script>
<script type="text/javascript" src="http://code.angularjs.org/1.2.9/angular-resource.min.js"></script>
<script type="text/javascript" src="/custom_assets/workerretrieval.js"></script>	
<script type="text/javascript" src="/custom_assets/angular-moment.js"></script>
<script type="text/javascript" src="/custom_assets/moment.js"></script>
<link rel="stylesheet" type="text/css" href="/custom_assets/custom.css"></link>
@stop

@section('modal')
<div ng-app="workerRetrieval" ng-controller="messageCtrl" ng-init="init()">
	<div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="messageModal" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h4 class="modal-title" id="myModalLabel">Message</h4>
	      </div>
		  <div class="modal-body">
	 		<label class="ann-label">To:</label> @{{recipient}}<br>
	 		<label for="subject" class="ann-label">Subject: </label><input id="subject" type="text"><br>
	 		<input type="textarea" class="messagecontent">
		  </div>
	      <div class="modal-footer">
    	     <button type="button" class="btn btn-primary" ng-click="sendMessage()">Send message</button>
	      </div>
	    </div>
	  </div>
  </div>
</div> 
@stop

@section('content')
<div ng-app="workerRetrieval" ng-controller="workerByIdCtrl">
	<!-- Main column with results -->
	@include('layouts.flashdata')
	<div class="row">
		
			<div class="ng-scope disabled pull-left">
				<ul style="margin-left: 20px;" class="pagination ng-isolate-scope">
					<li><a ng-click="gotoOverview()">Back to overview</a></li>
				</ul>
			</div>
			<div class="ng-scope space-left pull-left"> 
				<ul class="pagination ng-isolate-scope">
	          		<li><a class="ng-binding" ng-click="flagWorker()">Flag worker</a></li>
	          		<li><a class="ng-binding" data-toggle="modal" ng-click="gotoMessage()" data-target="#messageModal">Message worker</a></li>
	          	</ul>
			</div>
	</div>

	<div class="mainContainer">
		<div class="bordered">
			<div class="row">
           		<div class="col-md-8">
           			<h2>@{{worker.softwareAgent_id}}  @{{worker.platformAgentId}}</h2>
           			<div class="wp-from"><span ng-show="worker.city">@{{worker.city}},</span><span ng-show="worker.region"> @{{worker.region}},</span> @{{worker.country}}</div>
           			<div class="wp-created">First seen: @{{worker.created_at}}</div>
           		</div>
           		<div class="col-md-2 box-icon">
           			<strong style="font-size: 12pt;"><i class="fa fa-file fa-2x"></i><br>Favourite task</strong> 
           		</div>
          		<div class="col-md-2 box-icon right-end">
           			<strong style="font-size: 12pt; "><i class="fa fa-clock-o fa-2x"></i><br><span am-time-ago="worker.updated_at"></span></strong>
           		</div>	
           	</div>
		</div>
		<!-- <div class="bordered" style=" background: #FFF; padding: 10px;">
			<strong style="font-size: 12pt;"><i class="fa fa-list fa-2x"></i><br>12</strong> 
		</div> -->
		<div class="bordered">
			<div class="pull-left"><i class="fa fa-gavel ann-icon"></i></div><div><h4>Annotations</h4></div>
			<div ng-repeat="annotation in worker.has_generated_annotations" class="annotations">
				<div class="row">
					<div class="col-md-9">
						<h4>@{{annotation.format}} @{{annotation.domain}}</h4>
						<label class="ann-label">Unit:  </label>@{{annotation.unit_id}}<br>
						<label class="ann-label">Part of:  </label>@{{annotation.job_id}}<br>
						<label class="ann-label">Generated by:  </label>@{{annotation.activity_id}}
					</div>
					<div class="col-md-3 anntime">
						<label class="ann-label">Accepted: </label>@{{annotation.acceptTime}}<br>
						<label class="ann-label">Submitted: </label>@{{annotation.submitTime}}
					</div>
				</div>
				<div>
					<pre>@{{annotation.content}}</pre>
				</div>
			</div>
		</div>
	</div>

</div>
@stop

@section('end_javascript')
	<script>
				
	</script>
@stop